Loading data into Pandas

In [1]:
import pandas as pd 


# df_xlsx = pd.read_excel("pokemon_data.xlsx")
# print(df_xlsx)

# df_txt = pd.read_csv("pokemon_data.txt",delimiter="\t")
# print(df_txt)

df = pd.read_csv("pokemon_data.csv")
print(df)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49
1      2                Ivysaur    Grass  Poison  60      62       63
2      3               Venusaur    Grass  Poison  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123
4      4             Charmander     Fire     NaN  39      52       43
..   ...                    ...      ...     ...  ..     ...      ...
795  719                Diancie     Rock   Fairy  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60
799  721              Volcanion     Fire   Water  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 12 columns]

In [2]:
df.head(10)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False

# Reading Data in Pandas

In [3]:
## Read Headers 
# df.columns


## Read each column
# df['Legendary'] 
# df.Legendary


# print(df.iloc[0:4]) ## interger location

# # Read the specific Location (R,C)
# print(df.iloc[0,:-2])

In [4]:
for index,row in df.iterrows():
    print(index,row.Name,row["Type 1"])

0 Bulbasaur Grass
1 Ivysaur Grass
2 Venusaur Grass
3 VenusaurMega Venusaur Grass
4 Charmander Fire
5 Charmeleon Fire
6 Charizard Fire
7 CharizardMega Charizard X Fire
8 CharizardMega Charizard Y Fire
9 Squirtle Water
10 Wartortle Water
11 Blastoise Water
12 BlastoiseMega Blastoise Water
13 Caterpie Bug
14 Metapod Bug
15 Butterfree Bug
16 Weedle Bug
17 Kakuna Bug
18 Beedrill Bug
19 BeedrillMega Beedrill Bug
20 Pidgey Normal
21 Pidgeotto Normal
22 Pidgeot Normal
23 PidgeotMega Pidgeot Normal
24 Rattata Normal
25 Raticate Normal
26 Spearow Normal
27 Fearow Normal
28 Ekans Poison
29 Arbok Poison
30 Pikachu Electric
31 Raichu Electric
32 Sandshrew Ground
33 Sandslash Ground
34 Nidoran (Female) Poison
35 Nidorina Poison
36 Nidoqueen Poison
37 Nidoran (Male) Poison
38 Nidorino Poison
39 Nidoking Poison
40 Clefairy Fairy
41 Clefable Fairy
42 Vulpix Fire
43 Ninetales Fire
44 Jigglypuff Normal
45 Wigglytuff Normal
46 Zubat Poison
47 Golbat Poison
48 Oddish Grass
49 Gloom Grass
50 Vileplume Grass
51 Paras Bug
52 Parasect Bug
53 Venonat Bug
54 Venomoth Bug
55 Diglett Ground
56 Dugtrio Ground
57 Meowth Normal
58 Persian Normal
59 Psyduck Water
60 Golduck Water
61 Mankey Fighting
62 Primeape Fighting
63 Growlithe Fire
64 Arcanine Fire
65 Poliwag Water
66 Poliwhirl Water
67 Poliwrath Water
68 Abra Psychic
69 Kadabra Psychic
70 Alakazam Psychic
71 AlakazamMega Alakazam Psychic
72 Machop Fighting
73 Machoke Fighting
74 Machamp Fighting
75 Bellsprout Grass
76 Weepinbell Grass
77 Victreebel Grass
78 Tentacool Water
79 Tentacruel Water
80 Geodude Rock
81 Graveler Rock
82 Golem Rock
83 Ponyta Fire
84 Rapidash Fire
85 Slowpoke Water
86 Slowbro Water
87 SlowbroMega Slowbro Water
88 Magnemite Electric
89 Magneton Electric
90 Farfetch'd Normal
91 Doduo Normal
92 Dodrio Normal
93 Seel Water
94 Dewgong Water
95 Grimer Poison
96 Muk Poison
97 Shellder Water
98 Cloyster Water
99 Gastly Ghost
100 Haunter Ghost
101 Gengar Ghost
102 GengarMega Gengar Ghost
103 Onix Rock
104 Drowzee Psychic
105 Hypno Psychic
106 Krabby Water
107 Kingler Water
108 Voltorb Electric
109 Electrode Electric
110 Exeggcute Grass
111 Exeggutor Grass
112 Cubone Ground
113 Marowak Ground
114 Hitmonlee Fighting
115 Hitmonchan Fighting
116 Lickitung Normal
117 Koffing Poison
118 Weezing Poison
119 Rhyhorn Ground
120 Rhydon Ground
121 Chansey Normal
122 Tangela Grass
123 Kangaskhan Normal
124 KangaskhanMega Kangaskhan Normal
125 Horsea Water
126 Seadra Water
127 Goldeen Water
128 Seaking Water
129 Staryu Water
130 Starmie Water
131 Mr. Mime Psychic
132 Scyther Bug
133 Jynx Ice
134 Electabuzz Electric
135 Magmar Fire
136 Pinsir Bug
137 PinsirMega Pinsir Bug
138 Tauros Normal
139 Magikarp Water
140 Gyarados Water
141 GyaradosMega Gyarados Water
142 Lapras Water
143 Ditto Normal
144 Eevee Normal
145 Vaporeon Water
146 Jolteon Electric
147 Flareon Fire
148 Porygon Normal
149 Omanyte Rock
150 Omastar Rock
151 Kabuto Rock
152 Kabutops Rock
153 Aerodactyl Rock
154 AerodactylMega Aerodactyl Rock
155 Snorlax Normal
156 Articuno Ice
157 Zapdos Electric
158 Moltres Fire
159 Dratini Dragon
160 Dragonair Dragon
161 Dragonite Dragon
162 Mewtwo Psychic
163 MewtwoMega Mewtwo X Psychic
164 MewtwoMega Mewtwo Y Psychic
165 Mew Psychic
166 Chikorita Grass
167 Bayleef Grass
168 Meganium Grass
169 Cyndaquil Fire
170 Quilava Fire
171 Typhlosion Fire
172 Totodile Water
173 Croconaw Water
174 Feraligatr Water
175 Sentret Normal
176 Furret Normal
177 Hoothoot Normal
178 Noctowl Normal
179 Ledyba Bug
180 Ledian Bug
181 Spinarak Bug
182 Ariados Bug
183 Crobat Poison
184 Chinchou Water
185 Lanturn Water
186 Pichu Electric
187 Cleffa Fairy
188 Igglybuff Normal
189 Togepi Fairy
190 Togetic Fairy
191 Natu Psychic
192 Xatu Psychic
193 Mareep Electric
194 Flaaffy Electric
195 Ampharos Electric
196 AmpharosMega Ampharos Electric
197 Bellossom Grass
198 Marill Water
199 Azumarill Water
200 Sudowoodo Rock
201 Politoed Water
202 Hoppip Grass
203 Skiploom Grass
204 Jumpluff Grass
205 Aipom Normal
206 Sunkern Grass
207 Sunflora Grass
208 Yanma Bug
209 Wooper Water
210 Quagsire Water
211 Espeon Psychic
212 Umbreon Dark
213 Murkrow Dark
214 Slowking Water
215 Misdreavus Ghost
216 Unown Psychic
217 Wobbuffet Psychic
218 Girafarig Normal
219 Pineco Bug
220 Forretress Bug
221 Dunsparce Normal
222 Gligar Ground
223 Steelix Steel
224 SteelixMega Steelix Steel
225 Snubbull Fairy
226 Granbull Fairy
227 Qwilfish Water
228 Scizor Bug
229 ScizorMega Scizor Bug
230 Shuckle Bug
231 Heracross Bug
232 HeracrossMega Heracross Bug
233 Sneasel Dark
234 Teddiursa Normal
235 Ursaring Normal
236 Slugma Fire
237 Magcargo Fire
238 Swinub Ice
239 Piloswine Ice
240 Corsola Water
241 Remoraid Water
242 Octillery Water
243 Delibird Ice
244 Mantine Water
245 Skarmory Steel
246 Houndour Dark
247 Houndoom Dark
248 HoundoomMega Houndoom Dark
249 Kingdra Water
250 Phanpy Ground
251 Donphan Ground
252 Porygon2 Normal
253 Stantler Normal
254 Smeargle Normal
255 Tyrogue Fighting
256 Hitmontop Fighting
257 Smoochum Ice
258 Elekid Electric
259 Magby Fire
260 Miltank Normal
261 Blissey Normal
262 Raikou Electric
263 Entei Fire
264 Suicune Water
265 Larvitar Rock
266 Pupitar Rock
267 Tyranitar Rock
268 TyranitarMega Tyranitar Rock
269 Lugia Psychic
270 Ho-oh Fire
271 Celebi Psychic
272 Treecko Grass
273 Grovyle Grass
274 Sceptile Grass
275 SceptileMega Sceptile Grass
276 Torchic Fire
277 Combusken Fire
278 Blaziken Fire
279 BlazikenMega Blaziken Fire
280 Mudkip Water
281 Marshtomp Water
282 Swampert Water
283 SwampertMega Swampert Water
284 Poochyena Dark
285 Mightyena Dark
286 Zigzagoon Normal
287 Linoone Normal
288 Wurmple Bug
289 Silcoon Bug
290 Beautifly Bug
291 Cascoon Bug
292 Dustox Bug
293 Lotad Water
294 Lombre Water
295 Ludicolo Water
296 Seedot Grass
297 Nuzleaf Grass
298 Shiftry Grass
299 Taillow Normal
300 Swellow Normal
301 Wingull Water
302 Pelipper Water
303 Ralts Psychic
304 Kirlia Psychic
305 Gardevoir Psychic
306 GardevoirMega Gardevoir Psychic
307 Surskit Bug
308 Masquerain Bug
309 Shroomish Grass
310 Breloom Grass
311 Slakoth Normal
312 Vigoroth Normal
313 Slaking Normal
314 Nincada Bug
315 Ninjask Bug
316 Shedinja Bug
317 Whismur Normal
318 Loudred Normal
319 Exploud Normal
320 Makuhita Fighting
321 Hariyama Fighting
322 Azurill Normal
323 Nosepass Rock
324 Skitty Normal
325 Delcatty Normal
326 Sableye Dark
327 SableyeMega Sableye Dark
328 Mawile Steel
329 MawileMega Mawile Steel
330 Aron Steel
331 Lairon Steel
332 Aggron Steel
333 AggronMega Aggron Steel
334 Meditite Fighting
335 Medicham Fighting
336 MedichamMega Medicham Fighting
337 Electrike Electric
338 Manectric Electric
339 ManectricMega Manectric Electric
340 Plusle Electric
341 Minun Electric
342 Volbeat Bug
343 Illumise Bug
344 Roselia Grass
345 Gulpin Poison
346 Swalot Poison
347 Carvanha Water
348 Sharpedo Water
349 SharpedoMega Sharpedo Water
350 Wailmer Water
351 Wailord Water
352 Numel Fire
353 Camerupt Fire
354 CameruptMega Camerupt Fire
355 Torkoal Fire
356 Spoink Psychic
357 Grumpig Psychic
358 Spinda Normal
359 Trapinch Ground
360 Vibrava Ground
361 Flygon Ground
362 Cacnea Grass
363 Cacturne Grass
364 Swablu Normal
365 Altaria Dragon
366 AltariaMega Altaria Dragon
367 Zangoose Normal
368 Seviper Poison
369 Lunatone Rock
370 Solrock Rock
371 Barboach Water
372 Whiscash Water
373 Corphish Water
374 Crawdaunt Water
375 Baltoy Ground
376 Claydol Ground
377 Lileep Rock
378 Cradily Rock
379 Anorith Rock
380 Armaldo Rock
381 Feebas Water
382 Milotic Water
383 Castform Normal
384 Kecleon Normal
385 Shuppet Ghost
386 Banette Ghost
387 BanetteMega Banette Ghost
388 Duskull Ghost
389 Dusclops Ghost
390 Tropius Grass
391 Chimecho Psychic
392 Absol Dark
393 AbsolMega Absol Dark
394 Wynaut Psychic
395 Snorunt Ice
396 Glalie Ice
397 GlalieMega Glalie Ice
398 Spheal Ice
399 Sealeo Ice
400 Walrein Ice
401 Clamperl Water
402 Huntail Water
403 Gorebyss Water
404 Relicanth Water
405 Luvdisc Water
406 Bagon Dragon
407 Shelgon Dragon
408 Salamence Dragon
409 SalamenceMega Salamence Dragon
410 Beldum Steel
411 Metang Steel
412 Metagross Steel
413 MetagrossMega Metagross Steel
414 Regirock Rock
415 Regice Ice
416 Registeel Steel
417 Latias Dragon
418 LatiasMega Latias Dragon
419 Latios Dragon
420 LatiosMega Latios Dragon
421 Kyogre Water
422 KyogrePrimal Kyogre Water
423 Groudon Ground
424 GroudonPrimal Groudon Ground
425 Rayquaza Dragon
426 RayquazaMega Rayquaza Dragon
427 Jirachi Steel
428 DeoxysNormal Forme Psychic
429 DeoxysAttack Forme Psychic
430 DeoxysDefense Forme Psychic
431 DeoxysSpeed Forme Psychic
432 Turtwig Grass
433 Grotle Grass
434 Torterra Grass
435 Chimchar Fire
436 Monferno Fire
437 Infernape Fire
438 Piplup Water
439 Prinplup Water
440 Empoleon Water
441 Starly Normal
442 Staravia Normal
443 Staraptor Normal
444 Bidoof Normal
445 Bibarel Normal
446 Kricketot Bug
447 Kricketune Bug
448 Shinx Electric
449 Luxio Electric
450 Luxray Electric
451 Budew Grass
452 Roserade Grass
453 Cranidos Rock
454 Rampardos Rock
455 Shieldon Rock
456 Bastiodon Rock
457 Burmy Bug
458 WormadamPlant Cloak Bug
459 WormadamSandy Cloak Bug
460 WormadamTrash Cloak Bug
461 Mothim Bug
462 Combee Bug
463 Vespiquen Bug
464 Pachirisu Electric
465 Buizel Water
466 Floatzel Water
467 Cherubi Grass
468 Cherrim Grass
469 Shellos Water
470 Gastrodon Water
471 Ambipom Normal
472 Drifloon Ghost
473 Drifblim Ghost
474 Buneary Normal
475 Lopunny Normal
476 LopunnyMega Lopunny Normal
477 Mismagius Ghost
478 Honchkrow Dark
479 Glameow Normal
480 Purugly Normal
481 Chingling Psychic
482 Stunky Poison
483 Skuntank Poison
484 Bronzor Steel
485 Bronzong Steel
486 Bonsly Rock
487 Mime Jr. Psychic
488 Happiny Normal
489 Chatot Normal
490 Spiritomb Ghost
491 Gible Dragon
492 Gabite Dragon
493 Garchomp Dragon
494 GarchompMega Garchomp Dragon
495 Munchlax Normal
496 Riolu Fighting
497 Lucario Fighting
498 LucarioMega Lucario Fighting
499 Hippopotas Ground
500 Hippowdon Ground
501 Skorupi Poison
502 Drapion Poison
503 Croagunk Poison
504 Toxicroak Poison
505 Carnivine Grass
506 Finneon Water
507 Lumineon Water
508 Mantyke Water
509 Snover Grass
510 Abomasnow Grass
511 AbomasnowMega Abomasnow Grass
512 Weavile Dark
513 Magnezone Electric
514 Lickilicky Normal
515 Rhyperior Ground
516 Tangrowth Grass
517 Electivire Electric
518 Magmortar Fire
519 Togekiss Fairy
520 Yanmega Bug
521 Leafeon Grass
522 Glaceon Ice
523 Gliscor Ground
524 Mamoswine Ice
525 Porygon-Z Normal
526 Gallade Psychic
527 GalladeMega Gallade Psychic
528 Probopass Rock
529 Dusknoir Ghost
530 Froslass Ice
531 Rotom Electric
532 RotomHeat Rotom Electric
533 RotomWash Rotom Electric
534 RotomFrost Rotom Electric
535 RotomFan Rotom Electric
536 RotomMow Rotom Electric
537 Uxie Psychic
538 Mesprit Psychic
539 Azelf Psychic
540 Dialga Steel
541 Palkia Water
542 Heatran Fire
543 Regigigas Normal
544 GiratinaAltered Forme Ghost
545 GiratinaOrigin Forme Ghost
546 Cresselia Psychic
547 Phione Water
548 Manaphy Water
549 Darkrai Dark
550 ShayminLand Forme Grass
551 ShayminSky Forme Grass
552 Arceus Normal
553 Victini Psychic
554 Snivy Grass
555 Servine Grass
556 Serperior Grass
557 Tepig Fire
558 Pignite Fire
559 Emboar Fire
560 Oshawott Water
561 Dewott Water
562 Samurott Water
563 Patrat Normal
564 Watchog Normal
565 Lillipup Normal
566 Herdier Normal
567 Stoutland Normal
568 Purrloin Dark
569 Liepard Dark
570 Pansage Grass
571 Simisage Grass
572 Pansear Fire
573 Simisear Fire
574 Panpour Water
575 Simipour Water
576 Munna Psychic
577 Musharna Psychic
578 Pidove Normal
579 Tranquill Normal
580 Unfezant Normal
581 Blitzle Electric
582 Zebstrika Electric
583 Roggenrola Rock
584 Boldore Rock
585 Gigalith Rock
586 Woobat Psychic
587 Swoobat Psychic
588 Drilbur Ground
589 Excadrill Ground
590 Audino Normal
591 AudinoMega Audino Normal
592 Timburr Fighting
593 Gurdurr Fighting
594 Conkeldurr Fighting
595 Tympole Water
596 Palpitoad Water
597 Seismitoad Water
598 Throh Fighting
599 Sawk Fighting
600 Sewaddle Bug
601 Swadloon Bug
602 Leavanny Bug
603 Venipede Bug
604 Whirlipede Bug
605 Scolipede Bug
606 Cottonee Grass
607 Whimsicott Grass
608 Petilil Grass
609 Lilligant Grass
610 Basculin Water
611 Sandile Ground
612 Krokorok Ground
613 Krookodile Ground
614 Darumaka Fire
615 DarmanitanStandard Mode Fire
616 DarmanitanZen Mode Fire
617 Maractus Grass
618 Dwebble Bug
619 Crustle Bug
620 Scraggy Dark
621 Scrafty Dark
622 Sigilyph Psychic
623 Yamask Ghost
624 Cofagrigus Ghost
625 Tirtouga Water
626 Carracosta Water
627 Archen Rock
628 Archeops Rock
629 Trubbish Poison
630 Garbodor Poison
631 Zorua Dark
632 Zoroark Dark
633 Minccino Normal
634 Cinccino Normal
635 Gothita Psychic
636 Gothorita Psychic
637 Gothitelle Psychic
638 Solosis Psychic
639 Duosion Psychic
640 Reuniclus Psychic
641 Ducklett Water
642 Swanna Water
643 Vanillite Ice
644 Vanillish Ice
645 Vanilluxe Ice
646 Deerling Normal
647 Sawsbuck Normal
648 Emolga Electric
649 Karrablast Bug
650 Escavalier Bug
651 Foongus Grass
652 Amoonguss Grass
653 Frillish Water
654 Jellicent Water
655 Alomomola Water
656 Joltik Bug
657 Galvantula Bug
658 Ferroseed Grass
659 Ferrothorn Grass
660 Klink Steel
661 Klang Steel
662 Klinklang Steel
663 Tynamo Electric
664 Eelektrik Electric
665 Eelektross Electric
666 Elgyem Psychic
667 Beheeyem Psychic
668 Litwick Ghost
669 Lampent Ghost
670 Chandelure Ghost
671 Axew Dragon
672 Fraxure Dragon
673 Haxorus Dragon
674 Cubchoo Ice
675 Beartic Ice
676 Cryogonal Ice
677 Shelmet Bug
678 Accelgor Bug
679 Stunfisk Ground
680 Mienfoo Fighting
681 Mienshao Fighting
682 Druddigon Dragon
683 Golett Ground
684 Golurk Ground
685 Pawniard Dark
686 Bisharp Dark
687 Bouffalant Normal
688 Rufflet Normal
689 Braviary Normal
690 Vullaby Dark
691 Mandibuzz Dark
692 Heatmor Fire
693 Durant Bug
694 Deino Dark
695 Zweilous Dark
696 Hydreigon Dark
697 Larvesta Bug
698 Volcarona Bug
699 Cobalion Steel
700 Terrakion Rock
701 Virizion Grass
702 TornadusIncarnate Forme Flying
703 TornadusTherian Forme Flying
704 ThundurusIncarnate Forme Electric
705 ThundurusTherian Forme Electric
706 Reshiram Dragon
707 Zekrom Dragon
708 LandorusIncarnate Forme Ground
709 LandorusTherian Forme Ground
710 Kyurem Dragon
711 KyuremBlack Kyurem Dragon
712 KyuremWhite Kyurem Dragon
713 KeldeoOrdinary Forme Water
714 KeldeoResolute Forme Water
715 MeloettaAria Forme Normal
716 MeloettaPirouette Forme Normal
717 Genesect Bug
718 Chespin Grass
719 Quilladin Grass
720 Chesnaught Grass
721 Fennekin Fire
722 Braixen Fire
723 Delphox Fire
724 Froakie Water
725 Frogadier Water
726 Greninja Water
727 Bunnelby Normal
728 Diggersby Normal
729 Fletchling Normal
730 Fletchinder Fire
731 Talonflame Fire
732 Scatterbug Bug
733 Spewpa Bug
734 Vivillon Bug
735 Litleo Fire
736 Pyroar Fire
737 Flabébé Fairy
738 Floette Fairy
739 Florges Fairy
740 Skiddo Grass
741 Gogoat Grass
742 Pancham Fighting
743 Pangoro Fighting
744 Furfrou Normal
745 Espurr Psychic
746 MeowsticMale Psychic
747 MeowsticFemale Psychic
748 Honedge Steel
749 Doublade Steel
750 AegislashBlade Forme Steel
751 AegislashShield Forme Steel
752 Spritzee Fairy
753 Aromatisse Fairy
754 Swirlix Fairy
755 Slurpuff Fairy
756 Inkay Dark
757 Malamar Dark
758 Binacle Rock
759 Barbaracle Rock
760 Skrelp Poison
761 Dragalge Poison
762 Clauncher Water
763 Clawitzer Water
764 Helioptile Electric
765 Heliolisk Electric
766 Tyrunt Rock
767 Tyrantrum Rock
768 Amaura Rock
769 Aurorus Rock
770 Sylveon Fairy
771 Hawlucha Fighting
772 Dedenne Electric
773 Carbink Rock
774 Goomy Dragon
775 Sliggoo Dragon
776 Goodra Dragon
777 Klefki Steel
778 Phantump Ghost
779 Trevenant Ghost
780 PumpkabooAverage Size Ghost
781 PumpkabooSmall Size Ghost
782 PumpkabooLarge Size Ghost
783 PumpkabooSuper Size Ghost
784 GourgeistAverage Size Ghost
785 GourgeistSmall Size Ghost
786 GourgeistLarge Size Ghost
787 GourgeistSuper Size Ghost
788 Bergmite Ice
789 Avalugg Ice
790 Noibat Flying
791 Noivern Flying
792 Xerneas Fairy
793 Yveltal Dark
794 Zygarde50% Forme Dragon
795 Diancie Rock
796 DiancieMega Diancie Rock
797 HoopaHoopa Confined Psychic
798 HoopaHoopa Unbound Psychic
799 Volcanion Fire

In [5]:
df.loc[df["Type 1"]=="Grass"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

# Sorting And Describing Data

In [6]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [7]:
df.sort_values(["Name"],ascending=False)
df.sort_values(["Type 1","HP"],ascending=[1,0])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

# Making changes to the data

In [8]:
# df["Total"] = df.HP+df.Attack+df.Defense+df["Sp. Atk"]+df["Sp. Def"]+df.Speed
df["Total"] = df.iloc[:,4:10].sum(axis=1)
# df.sort_values(["Total"],ascending=False) 

cols = list(df.columns)
df = df[cols[0:4] + cols[-2:] + cols[4:11]]

df

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,False,309,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,True,600,50,100,150,100,150,50,6
796,719,DiancieMega Diancie,Rock,Fairy,True,700,50,160,110,160,110,110,6
797,720,HoopaHoopa Confined,Psychic,Ghost,True,600,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,Dark,True,680,80,160,60,170,130,80,6
799,721,Volcanion,Fire,Water,True,600,80,110,120,130,90,70,6

# Saving our Data

In [9]:
df.to_csv("modified.csv",index=False)

In [10]:
df2 = pd.read_csv("modified.csv")

# Filtering Data

In [11]:
filtered_data = df.loc[(df['Type 1']=='Grass') & (df['Type 2'] == 'Poison') & (df['HP']>70)]
filtered_data.to_csv("New Filtered.csv")
# filtered_data.reset_index(drop=True,inplace=True)
filtered_data

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
50,45,Vileplume,Grass,Poison,False,490,75,80,85,110,90,50,1
77,71,Victreebel,Grass,Poison,False,490,80,105,65,100,70,70,1
652,591,Amoonguss,Grass,Poison,False,464,114,85,70,85,80,30,5

In [16]:
df.loc[~df['Name'].str.contains('Mega')] 
# ~ this is the symbol not in pandas 
# df.loc[df["Type 1"]=="Fire","Type 1"] = "Flamer" 
# df.loc[df["Type 1"]=="Flamer",'Type 1'] = "Fire"
df.loc[df['Type 1']=="Fire","Legendary"] = True

In [17]:
df

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,True,309,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,True,600,50,100,150,100,150,50,6
796,719,DiancieMega Diancie,Rock,Fairy,True,700,50,160,110,160,110,110,6
797,720,HoopaHoopa Confined,Psychic,Ghost,True,600,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,Dark,True,680,80,160,60,170,130,80,6
799,721,Volcanion,Fire,Water,True,600,80,110,120,130,90,70,6

# Conditional Changes

In [40]:
df.loc[df["Total"]>500,["Generation,Legendary"]]="Test value"

C:\Users\Qasim\AppData\Local\Temp\ipykernel_6556\2462704779.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Test value' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df["Total"]>500,["Generation,Legendary"]]="Test value"

In [35]:
df = pd.read_csv("modified.csv")

In [39]:
df = df.replace("Test value", 1)
df

C:\Users\Qasim\AppData\Local\Temp\ipykernel_6556\3429184404.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("Test value", 1)

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,"Generation,Legendary"
0,1,Bulbasaur,Grass,Poison,False,318,45,49,49,65,65,45,1,NaN
1,2,Ivysaur,Grass,Poison,False,405,60,62,63,80,80,60,1,NaN
2,3,Venusaur,Grass,Poison,False,525,80,82,83,100,100,80,1,1.0
3,3,VenusaurMega Venusaur,Grass,Poison,False,625,80,100,123,122,120,80,1,1.0
4,4,Charmander,Fire,NaN,False,309,39,52,43,60,50,65,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,True,600,50,100,150,100,150,50,6,1.0
796,719,DiancieMega Diancie,Rock,Fairy,True,700,50,160,110,160,110,110,6,1.0
797,720,HoopaHoopa Confined,Psychic,Ghost,True,600,80,110,60,150,130,70,6,1.0
798,720,HoopaHoopa Unbound,Psychic,Dark,True,680,80,160,60,170,130,80,6,1.0
799,721,Volcanion,Fire,Water,True,600,80,110,120,130,90,70,6,1.0